print("               BIODATA MAHASISWA                  ")
print("==================================================")
print("Nama Lengkap    : Maulani Almufida Ilmi")
print("NIM             : 2611531006")
print("Fakultas        : Teknologi Informasi")
print("Departemen      : Informatika")
print("Universitas     : Universitas Andalas")
print("Tahun Angkatan  : 2026")
print("Mata Kuliah     : Praktikum Algoritma & Pemrograman")

print("Status Program  : Berhasil Dijalankan")
print("==================================================")